### PR TITLE
Make scripts executable from anywhere in the system

### PR DESCRIPTION
**Pull request by 0Nel**
This allows for running ./exec.bash and ./stop.bash from anywhere. Workspace and other files (e.g. has_gou_support.txt etc.) are created in place.

The idea originated from making the source includes of relative scripts more robust. This however will be helpful for starting docker containers via other scripts or during startup.

### CODE REVIEW

**Comment by planthaber** [comment]
Looks good.

Would it make sense to use e.g. the .autocomplete.me script to add the root dir to the path, so one could just call exec.bash anywhere?

**Comment by 0Nel** [comment]
I dont fully understand your proposal. Could you please elaborate on that?

Indeed I didnt add the ROOT_DIR variable to the autocomplete.me script, which I will update as well for completeness. I thought it is not needed as my use case was triggering the exec.bash from my home directory. For this manual approach it would already be too costly to type the entire path twice and I would prefer to change dir once and continue with the old approach.

Regarding adding the path: do you mean having exec.bash as kind of like an alias? For me that wouldn't work as I have a bunch of docker workspaces with exec.bash scripts in my ~/docker directory. You must be in a similar situation aren't you? For clarification; you can already the exec.bash and stop.bash from anywhere in the system, if you use the full path. The following examples work already, without previous sourcing:

```
/$ ./home/user/docker/testing/exec.bash
~/home/user$> ./docker/testing/stop.bash
```

**Comment by planthaber** [comment]
That's what I meant, just calling ./exec from anywhere (e.g. the workspace folder, startscript folder, etc.). I thought this was also your use case ;-) .

We could think about adding an init script that adds the path and also sources the autocomplete.me (init.bash, env.bash, setup.bash, setup_console.bash). What do you think?

**Comment by 0Nel** [comment]
I am ambiguous about the idea of adding an init/env file. On the one hand I agree that it would be nice to source one obvious script and have everything in place. On the other hand I want to avoid that users think it would be mandatory to source a file first and then use the repo. I like that it is not that way and that basically everything works out of the box. I'd prefer to stick with autocomplete.me for now or come up with another less mandatory sounding script name. Examples from the top of my head, that I am not really satisfied with, would be `extend.me`, `convenience.bash` or  `magic.bash`. Do you have any other suggestions? If we reach a point were it is essential to source a file before things work, we could still move to a setup.bash/env.bash.

**Comment by planthaber** [comment]
Perhaps just stick with autocomplete.me and add the PATH there?

**Comment by 0Nel** [comment]
Done :thumbsup:

**Review by planthaber — APPROVED** [review]

**Pull request merged**
