### PR TITLE
Fix patching of dir mounts for CD build

### PR DESCRIPTION
**Pull request by 0Nel**

### CODE REVIEW

**Comment by 0Nel** [comment]
The previous approach was assuming that the ADDITIONAL_DOCKER_ARGS are spread over several lines and if not actually removed the entire line with all arguments. Now only the mount themselves are removed .

Open question: Should we patch away `--priviliged` as well? I think this would be a severe security issue, if it is allowed on the buildserver.

**Comment by planthaber** [comment]
There is no execution of user code in the build is it? So the risk is less, but when executing tests, this is in fact an issue

**Comment by 0Nel** [comment]
Since this is CD, where tests are part of the default pipeline user-code from inside the container could be executed.

Patched `--privileged` as well now. Added an additional DEBUG output.

**Comment by 0Nel** [comment]
Well thinking about this now.. While this adds another barrier for security, it wouldn't withstand any actual effort as the line I added could easily be removed manually :rofl:

**Pull request merged**
