### PR TITLE
Use single configfile instead one for each execmode and gpu support

### PR DESCRIPTION
**Pull request by planthaber**
This saves the image ids and the gpu support result into one single file: container_config.txt

Added bash-based read/write functions for that file.

It may still be deleted to rebuild a container, or just the value can be deleted from that file

### CODE REVIEW

**Comment by 0Nel** [comment]
First of I like the approach to aggregate all of the dangling config .txt files. However I feel that your approach makes it harder to delete individual containers. If I have a project in which I have a devel and release container, but I only want to delete the devel container I would have to edit the config file manually instead of conveniently removing the devel-container_id.txt file. I know this is not too much to ask, but I think the average user would not necessarily figure that out without reading the entire documentation and still I feel this extra step is making it less convenient. I have two proposals on how to solve this:

1. make a config directory (maybe hidden) and store all previously used txt files in it. This would allow to easily remove single containers just by prepending the config dir to the rm command argument. If the config dir is not hidden it could actually also be a place to store the settings.bash file. A little bit more hidden, but also the config dir, which indicates that it is a place to configure the project.

2. Use the approach that you have provided and add a simple purge.bash or purge_container.bash script that takes the exec mode as argument or reads it from the settings.bash and clears the corresponding line in the config file. This would add another file, but makes the whole how to delete a container approach more user friendly imo.

Personally I favor the second approach. Making the config file hidden would help to not confuse it with a file that allows manual configuration and having a script to purge containers would be a more obvious way than knowing the effect of deleting the respective txt file. Know that I think about this a purge.bash file could actually be used to purge either container or image. Maybe container by default and an image argument with user [y/n] prompt for images. Might even be sufficient to store the purge script to the tools directory.

**Comment by planthaber** [comment]
You can still just delete the container_config.txt file, only that it will clear all containers instead of an individual one.
But I guess most users will only use devel or release and only a few both.

A purge (or delete_container) script sounds nice, which will then also directly delete the container opposed to the current behavior (deleting it just before the next is created)

**Comment by planthaber** [comment]
Added the delete_container.bash script on top level

**Comment by 0Nel** [comment]
Okay, now with the delete script I am fine with this approach!

what do you think about enabling the delete script to also delete images. With additional argument and maybe even user prompt? We could also create a similar delete image script.

Do you prefer having the scripts in the root directory rather than in the tools dir? I get that it is a more obvious location, but I think if the main directory is as clean as possible it will automatically draw more attention to the directories and tools indicates helpful script right?

**Comment by planthaber** [comment]
I was thinking about the tools dir, but then decided to have the "most commonly used" (exec,stop,delete) scripts on to level.
I'd also see deleting the image as a more uncommon action and place that one in the tools folder. What do you think?

I made container_config.txt a hidden file, and added it to the gitignore file (so it is never checked in), so on fresh checkouts it doesn't even exist.

**Comment by planthaber** [comment]
Added the delete_image script (auto deletes container) ind tools folder

**Review by 0Nel — APPROVED** [review]
Looks good to me now :+1: 

The delete scripts don't need extra documentation right?

**Pull request merged**
