### PR TITLE
Create testsuite

### PR DESCRIPTION
**Pull request by 0Nel**
### Current state:

for base, devel and release mode
* run whoami in exec.bash
    => check if correct container user is used
    => check if container was started/is running
    => check if current container uses correct image
* run stop.bash
    => check exit status = 0
    => parse output and check if correct container is stopped
    => check that current container is not running anymore
    => check that current container exists as stopped container
    => check that stopped container is using the correct image
* run delete_container.bash
    => check exit status = 0
    => check that current container does not exist anymore
    
### To Test
- [ ] test version mismatch warning
- [ ] test storedrelease (store and remove)
- [x] test ownership of workspace in release image?

### To Be Discusses
- [x] use base user for base images?
- [ ] how should we test build.bash scripts? using dry-run approach?

### CODE REVIEW

**Comment by planthaber** [comment]
I think naming the new folder "src" may be misleading for devs startign to use this (they have to enter workspace instead).

something like "docker_scripts" whoulf be better imo

**Comment by planthaber** [comment]
Or even an hidden folder? ".docker_scripts"

**Comment by 0Nel** [comment]
I like the idea to have the scripts aka inner workings completely hidden from the user :+1:

What are your thoughts on the open questions I listed above?

**Comment by planthaber** [comment]
Actually setting PS1 works and makes different users obsolete (much cleaner Dockerfile for the release)

Created a PR to this branch: https://github.com/dfki-ric/docker_image_development/pull/35 we can discuss there (e.g. the format of the PS1 var)

**Comment by 0Nel** [comment]
Thanks for the PR regarding PS1. Much cleaner and also more informative promt :+1: 

Could you elaborate on your proposal to overwrite and auto_call setup_workspace. Do you want to add that as an additional test to the suite or is that an idea related on how to test the build.bash scripts?

Checking the extract workspace script is also a good idea.

**Comment by planthaber** [comment]
Hi, you can automate calls on container creation:
Internally there is the /opt/init_workspace.bash script:

created here:
https://github.com/dfki-ric/docker_image_development/blob/master/image_setup/01_base_images/prepare_image.bash#L37

called here:
https://github.com/dfki-ric/docker_image_development/blob/master/image_setup/01_base_images/check_init_workspace.bash
by 
https://github.com/dfki-ric/docker_image_development/blob/testsuite/.docker_scripts/docker_commands.bash#L84

It can be used to run scripts like setup_workspace.bash on container creation, currently we only use it to print the info to run
setup_workspace manually:
https://github.com/dfki-ric/docker_image_development/blob/testsuite/image_setup/02_devel_image/Dockerfile#L29

But we could also just run `echo /opt/setup_workspace  >> /opt/init_workspace.bash` in some Dockerfile to run stuff automatically.

**But for the testsuite is think it would be better to just use a script that creates some files using ./exec.bash (possibly using docker cp to place it in the devel container) and then check the permissions/access in the release**
If we don't declare permissions checks obsolete as there are no more user changes when building the release

**Comment by 0Nel** [comment]
As stated in your comment permission/access checks are indeed obsolete with the new dockeruser implementation.

I moved all open test_suite ToDos to a new issue (https://github.com/dfki-ric/docker_image_development/issues/36)

Removing the WIP tag now. Feel free to merge.

**Pull request merged**
